# Generated by Django 3.1.7 on 2021-04-02 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='brigade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='construction_management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=12)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.TextField()),
                ('tin', models.TextField()),
                ('telephone', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.TextField()),
                ('tag', models.TextField()),
                ('status', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='obj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_name', models.TextField()),
                ('finsih_to', models.DateField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.contract')),
            ],
        ),
        migrations.CreateModel(
            name='worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField()),
                ('telephone', models.CharField(max_length=12)),
                ('speciality', models.TextField()),
                ('passport', models.TextField()),
                ('is_brigadier', models.BooleanField()),
                ('brigade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.brigade')),
            ],
        ),
        migrations.CreateModel(
            name='work_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField()),
                ('started', models.DateField()),
                ('finished', models.DateField()),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.obj')),
            ],
        ),
        migrations.CreateModel(
            name='specification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField()),
                ('note', models.TextField()),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.obj')),
            ],
        ),
        migrations.CreateModel(
            name='sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('square', models.IntegerField()),
                ('management', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.construction_management')),
            ],
        ),
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_actual', models.DateField()),
                ('finished_actual', models.DateField()),
                ('work_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.work_type')),
            ],
        ),
        migrations.CreateModel(
            name='object_equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.equipment')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.obj')),
            ],
        ),
        migrations.AddField(
            model_name='obj',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.sector'),
        ),
        migrations.CreateModel(
            name='estimation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField()),
                ('quantity', models.IntegerField()),
                ('work_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.work_type')),
            ],
        ),
        migrations.CreateModel(
            name='engineering_staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField()),
                ('telephone', models.CharField(max_length=12)),
                ('position', models.TextField()),
                ('passport', models.TextField()),
                ('birth_date', models.DateField()),
                ('is_manager', models.BooleanField()),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.sector')),
            ],
        ),
        migrations.CreateModel(
            name='director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField()),
                ('telephone', models.CharField(max_length=12)),
                ('passport', models.TextField()),
                ('birth_date', models.DateField()),
                ('management', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.construction_management')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.customer'),
        ),
        migrations.CreateModel(
            name='consumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField()),
                ('quantity', models.IntegerField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.report')),
            ],
        ),
        migrations.AddField(
            model_name='brigade',
            name='work_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.work_type'),
        ),
    ]
