# Generated by Django 3.1.7 on 2021-05-02 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='brigade',
        ),
        migrations.AddField(
            model_name='worker',
            name='work_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='viewer.work_type'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='brigade',
        ),
    ]
