# Generated by Django 3.1.7 on 2021-05-05 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_auto_20210502_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='brigade',
        ),
        migrations.AddField(
            model_name='brigade',
            name='worker',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='viewer.worker'),
            preserve_default=False,
        ),
    ]
