# Generated by Django 3.1.7 on 2021-05-10 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_auto_20210505_1720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='construction_management',
            options={'ordering': ['id'], 'verbose_name': 'строительное управление', 'verbose_name_plural': 'строительные управления'},
        ),
        migrations.AlterModelOptions(
            name='consumption',
            options={'ordering': ['id'], 'verbose_name': 'расход', 'verbose_name_plural': 'расходы'},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['id'], 'verbose_name': 'договор', 'verbose_name_plural': 'договоры'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['id'], 'verbose_name': 'заказчик', 'verbose_name_plural': 'заказчики'},
        ),
        migrations.AlterModelOptions(
            name='director',
            options={'ordering': ['id'], 'verbose_name': 'руководитель строительного управления', 'verbose_name_plural': 'руководители строительного управления'},
        ),
        migrations.AlterModelOptions(
            name='engineering_staff',
            options={'ordering': ['id'], 'verbose_name': 'инженерно-технический персонал', 'verbose_name_plural': 'инженерно-технический персонал'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['id'], 'verbose_name': 'техника', 'verbose_name_plural': 'техника'},
        ),
        migrations.AlterModelOptions(
            name='estimation',
            options={'ordering': ['id'], 'verbose_name': 'смета', 'verbose_name_plural': 'сметы'},
        ),
        migrations.AlterModelOptions(
            name='obj',
            options={'ordering': ['id'], 'verbose_name': 'объект', 'verbose_name_plural': 'объекты'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['id'], 'verbose_name': 'отчёт', 'verbose_name_plural': 'отчёты'},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'ordering': ['id'], 'verbose_name': 'участок', 'verbose_name_plural': 'участки'},
        ),
        migrations.AlterModelOptions(
            name='specification',
            options={'ordering': ['id'], 'verbose_name': 'характеристика', 'verbose_name_plural': 'характеристики'},
        ),
        migrations.AlterModelOptions(
            name='work_type',
            options={'ordering': ['id'], 'verbose_name': 'вид работы', 'verbose_name_plural': 'виды работы'},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'ordering': ['id'], 'verbose_name': 'рабочий', 'verbose_name_plural': 'рабочие'},
        ),
        migrations.RemoveField(
            model_name='worker',
            name='is_brigadier',
        ),
        migrations.AlterField(
            model_name='brigade',
            name='work_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.work_type', verbose_name='Вид работы'),
        ),
        migrations.AlterField(
            model_name='brigade',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.worker', verbose_name='Рабочий'),
        ),
        migrations.AlterField(
            model_name='construction_management',
            name='address',
            field=models.TextField(verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='construction_management',
            name='telephone',
            field=models.CharField(max_length=12, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='consumption',
            name='item',
            field=models.TextField(verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='consumption',
            name='quantity',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='consumption',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.report', verbose_name='Отчет'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.customer', verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='total',
            field=models.IntegerField(verbose_name='Сумма всего, рубли'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_name',
            field=models.TextField(verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='telephone',
            field=models.CharField(max_length=12, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tin',
            field=models.TextField(verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='director',
            name='birth_date',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='director',
            name='full_name',
            field=models.TextField(verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='director',
            name='management',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.construction_management', verbose_name='Строительное управление'),
        ),
        migrations.AlterField(
            model_name='director',
            name='passport',
            field=models.TextField(verbose_name='Данные пасспорта'),
        ),
        migrations.AlterField(
            model_name='director',
            name='telephone',
            field=models.CharField(max_length=12, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='engineering_staff',
            name='birth_date',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='engineering_staff',
            name='full_name',
            field=models.TextField(verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='engineering_staff',
            name='is_manager',
            field=models.BooleanField(verbose_name='Является начальником участка'),
        ),
        migrations.AlterField(
            model_name='engineering_staff',
            name='passport',
            field=models.TextField(verbose_name='Данные пасспорта'),
        ),
        migrations.AlterField(
            model_name='engineering_staff',
            name='position',
            field=models.TextField(verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='engineering_staff',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.sector', verbose_name='Участок'),
        ),
        migrations.AlterField(
            model_name='engineering_staff',
            name='telephone',
            field=models.CharField(max_length=12, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.TextField(verbose_name='Тип техники'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.TextField(verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='tag',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='estimation',
            name='item',
            field=models.TextField(verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='estimation',
            name='quantity',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='estimation',
            name='work_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.work_type', verbose_name='Вид работы'),
        ),
        migrations.AlterField(
            model_name='obj',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.contract', verbose_name='Договор'),
        ),
        migrations.AlterField(
            model_name='obj',
            name='finsih_to',
            field=models.DateField(verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='obj',
            name='obj_name',
            field=models.TextField(verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='obj',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.sector', verbose_name='Участок'),
        ),
        migrations.AlterField(
            model_name='object_equipment',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.equipment', verbose_name='Техника'),
        ),
        migrations.AlterField(
            model_name='object_equipment',
            name='obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.obj', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='report',
            name='finished_actual',
            field=models.DateField(verbose_name='Реальная дата конца работы'),
        ),
        migrations.AlterField(
            model_name='report',
            name='started_actual',
            field=models.DateField(verbose_name='Реальная дата начала работы'),
        ),
        migrations.AlterField(
            model_name='report',
            name='work_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.work_type', verbose_name='Вид работы'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='address',
            field=models.TextField(verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='management',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.construction_management', verbose_name='Строительное управление'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='square',
            field=models.IntegerField(verbose_name='Площадь, кв. метры'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='note',
            field=models.TextField(verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='tag',
            field=models.TextField(verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='work_type',
            name='finished',
            field=models.DateField(verbose_name='Конец работы'),
        ),
        migrations.AlterField(
            model_name='work_type',
            name='obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.obj', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='work_type',
            name='started',
            field=models.DateField(verbose_name='Начало работы'),
        ),
        migrations.AlterField(
            model_name='work_type',
            name='tag',
            field=models.TextField(verbose_name='Вид работы'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='full_name',
            field=models.TextField(verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='passport',
            field=models.TextField(verbose_name='Данные пасспорта'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='speciality',
            field=models.TextField(verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='telephone',
            field=models.CharField(max_length=12, verbose_name='Номер телефона'),
        ),
    ]
