# Generated by Django 3.1.7 on 2021-05-10 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_auto_20210511_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='management',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='viewer.construction_management', verbose_name='Строительное управление'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='management',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='viewer.construction_management', verbose_name='Строительное управление'),
        ),
    ]
