# Generated by Django 3.1.7 on 2021-05-10 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_auto_20210511_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='management',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.construction_management', verbose_name='Строительное управление'),
        ),
    ]
