# Generated by Django 3.1.7 on 2021-05-12 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0007_auto_20210511_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumption',
            name='estimation',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='viewer.estimation', verbose_name='Смета'),
            preserve_default=False,
        ),
    ]
